-- Two-tier admin RBAC: SUPER_ADMIN (owner) above ADMIN (moderator).
--
-- Hand-written rather than generated by `prisma migrate dev`, because this
-- database already has four migrations applied that are absent from this
-- repo's migrations/ directory (add_religion_and_partner_preference,
-- add_feature_flags, add_email_verification, drop_legacy_tables). A generated
-- migration would have tried to reconcile that drift by resetting the
-- database. This file therefore contains ONLY the two changes this feature
-- needs, and is safe to apply on top of the live schema.

-- 1. The new role. Idempotent so a re-run is harmless.
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

-- 2. Attribution for feature-flag changes. The FeatureFlag table already
--    exists (add_feature_flags); this only adds the nullable author column.
--    ON DELETE SET NULL so removing an admin account never drops a flag.
ALTER TABLE "FeatureFlag" ADD COLUMN IF NOT EXISTS "updatedById" TEXT;

CREATE INDEX IF NOT EXISTS "FeatureFlag_updatedById_idx"
  ON "FeatureFlag"("updatedById");

DO $$
BEGIN
  ALTER TABLE "FeatureFlag"
    ADD CONSTRAINT "FeatureFlag_updatedById_fkey"
    FOREIGN KEY ("updatedById") REFERENCES "User"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
