/**
 * Bangladesh administrative geography (64 districts + upazilas).
 * `value` is the CANONICAL English value stored in the DB / used by search.
 * `bn` is the Bengali display label. Keep values stable.
 */

export interface GeoOption {
  value: string;
  bn: string;
}

export const UPAZILAS_BY_DISTRICT: Record<string, readonly GeoOption[]> = {
  // ---------------- Dhaka Division ----------------
  Dhaka: [
    { value: "Savar", bn: "সাভার" },
    { value: "Dhamrai", bn: "ধামরাই" },
    { value: "Keraniganj", bn: "কেরানীগঞ্জ" },
    { value: "Nawabganj", bn: "নবাবগঞ্জ" },
    { value: "Dohar", bn: "দোহার" },
    { value: "Other", bn: "অন্যান্য" },
  ],
  Gazipur: [
    { value: "Gazipur Sadar", bn: "গাজীপুর সদর" },
    { value: "Kaliganj", bn: "কালীগঞ্জ" },
    { value: "Kaliakair", bn: "কালিয়াকৈর" },
    { value: "Kapasia", bn: "কাপাসিয়া" },
    { value: "Sreepur", bn: "শ্রীপুর" },
  ],
  Kishoreganj: [
    { value: "Kishoreganj Sadar", bn: "কিশোরগঞ্জ সদর" },
    { value: "Bhairab", bn: "ভৈরব" },
    { value: "Katiadi", bn: "কটিয়াদী" },
    { value: "Karimganj", bn: "করিমগঞ্জ" },
    { value: "Tarail", bn: "তাড়াইল" },
    { value: "Hossainpur", bn: "হোসেনপুর" },
    { value: "Pakundia", bn: "পাকুন্দিয়া" },
    { value: "Kuliarchar", bn: "কুলিয়ারচর" },
    { value: "Bajitpur", bn: "বাজিতপুর" },
    { value: "Nikli", bn: "নিকলী" },
    { value: "Itna", bn: "ইটনা" },
    { value: "Mithamain", bn: "মিঠামইন" },
    { value: "Astagram", bn: "অষ্টগ্রাম" },
  ],
  Manikganj: [
    { value: "Manikganj Sadar", bn: "মানিকগঞ্জ সদর" },
    { value: "Singair", bn: "সিংগাইর" },
    { value: "Shibalaya", bn: "শিবালয়" },
    { value: "Saturia", bn: "সাটুরিয়া" },
    { value: "Harirampur", bn: "হরিরামপুর" },
    { value: "Ghior", bn: "ঘিওর" },
    { value: "Daulatpur", bn: "দৌলতপুর" },
  ],
  Munshiganj: [
    { value: "Munshiganj Sadar", bn: "মুন্সিগঞ্জ সদর" },
    { value: "Sreenagar", bn: "শ্রীনগর" },
    { value: "Sirajdikhan", bn: "সিরাজদিখান" },
    { value: "Louhajang", bn: "লৌহজং" },
    { value: "Gazaria", bn: "গজারিয়া" },
    { value: "Tongibari", bn: "টংগিবাড়ী" },
  ],
  Narayanganj: [
    { value: "Narayanganj Sadar", bn: "নারায়ণগঞ্জ সদর" },
    { value: "Araihazar", bn: "আড়াইহাজার" },
    { value: "Bandar", bn: "বন্দর" },
    { value: "Rupganj", bn: "রূপগঞ্জ" },
    { value: "Sonargaon", bn: "সোনারগাঁও" },
  ],
  Narsingdi: [
    { value: "Narsingdi Sadar", bn: "নরসিংদী সদর" },
    { value: "Belabo", bn: "বেলাবো" },
    { value: "Monohardi", bn: "মনোহরদী" },
    { value: "Palash", bn: "পলাশ" },
    { value: "Raipura", bn: "রায়পুরা" },
    { value: "Shibpur", bn: "শিবপুর" },
  ],
  Tangail: [
    { value: "Tangail Sadar", bn: "টাঙ্গাইল সদর" },
    { value: "Sakhipur", bn: "সখিপুর" },
    { value: "Basail", bn: "বাসাইল" },
    { value: "Madhupur", bn: "মধুপুর" },
    { value: "Ghatail", bn: "ঘাটাইল" },
    { value: "Kalihati", bn: "কালিহাতী" },
    { value: "Nagarpur", bn: "নাগরপুর" },
    { value: "Mirzapur", bn: "মির্জাপুর" },
    { value: "Gopalpur", bn: "গোপালপুর" },
    { value: "Delduar", bn: "দেলদুয়ার" },
    { value: "Bhuapur", bn: "ভূঞাপুর" },
    { value: "Dhanbari", bn: "ধনবাড়ী" },
  ],
  Faridpur: [
    { value: "Faridpur Sadar", bn: "ফরিদপুর সদর" },
    { value: "Alfadanga", bn: "আলফাডাঙ্গা" },
    { value: "Boalmari", bn: "বোয়ালমারী" },
    { value: "Sadarpur", bn: "সদরপুর" },
    { value: "Nagarkanda", bn: "নগরকান্দা" },
    { value: "Bhanga", bn: "ভাঙ্গা" },
    { value: "Charbhadrasan", bn: "চরভদ্রাসন" },
    { value: "Madhukhali", bn: "মধুখালী" },
    { value: "Saltha", bn: "সালথা" },
  ],
  Gopalganj: [
    { value: "Gopalganj Sadar", bn: "গোপালগঞ্জ সদর" },
    { value: "Kashiani", bn: "কাশিয়ানী" },
    { value: "Kotalipara", bn: "কোটালীপাড়া" },
    { value: "Muksudpur", bn: "মুকসুদপুর" },
    { value: "Tungipara", bn: "টুঙ্গিপাড়া" },
  ],
  Madaripur: [
    { value: "Madaripur Sadar", bn: "মাদারীপুর সদর" },
    { value: "Kalkini", bn: "কালকিনি" },
    { value: "Rajoir", bn: "রাজৈর" },
    { value: "Shibchar", bn: "শিবচর" },
  ],
  Rajbari: [
    { value: "Rajbari Sadar", bn: "রাজবাড়ী সদর" },
    { value: "Goalanda", bn: "গোয়ালন্দ" },
    { value: "Pangsha", bn: "পাংশা" },
    { value: "Baliakandi", bn: "বালিয়াকান্দি" },
    { value: "Kalukhali", bn: "কালুখালী" },
  ],
  Shariatpur: [
    { value: "Shariatpur Sadar", bn: "শরীয়তপুর সদর" },
    { value: "Naria", bn: "নড়িয়া" },
    { value: "Zajira", bn: "জাজিরা" },
    { value: "Gosairhat", bn: "গোসাইরহাট" },
    { value: "Bhedarganj", bn: "ভেদরগঞ্জ" },
    { value: "Damudya", bn: "ডামুড্যা" },
  ],

  // ---------------- Chattogram Division ----------------
  Chattogram: [
    { value: "Chattogram Sadar", bn: "চট্টগ্রাম সদর" },
    { value: "Mirsharai", bn: "মীরসরাই" },
    { value: "Sitakunda", bn: "সীতাকুণ্ড" },
    { value: "Sandwip", bn: "সন্দ্বীপ" },
    { value: "Fatikchhari", bn: "ফটিকছড়ি" },
    { value: "Hathazari", bn: "হাটহাজারী" },
    { value: "Raozan", bn: "রাউজান" },
    { value: "Rangunia", bn: "রাঙ্গুনিয়া" },
    { value: "Boalkhali", bn: "বোয়ালখালী" },
    { value: "Patiya", bn: "পটিয়া" },
    { value: "Anwara", bn: "আনোয়ারা" },
    { value: "Chandanaish", bn: "চন্দনাইশ" },
    { value: "Satkania", bn: "সাতকানিয়া" },
    { value: "Lohagara", bn: "লোহাগাড়া" },
    { value: "Banshkhali", bn: "বাঁশখালী" },
    { value: "Other", bn: "অন্যান্য" },
  ],
  "Cox's Bazar": [
    { value: "Cox's Bazar Sadar", bn: "কক্সবাজার সদর" },
    { value: "Chakaria", bn: "চকরিয়া" },
    { value: "Teknaf", bn: "টেকনাফ" },
    { value: "Ukhia", bn: "উখিয়া" },
    { value: "Ramu", bn: "রামু" },
    { value: "Maheshkhali", bn: "মহেশখালী" },
    { value: "Kutubdia", bn: "কুতুবদিয়া" },
    { value: "Pekua", bn: "পেকুয়া" },
  ],
  Bandarban: [
    { value: "Bandarban Sadar", bn: "বান্দরবান সদর" },
    { value: "Thanchi", bn: "থানচি" },
    { value: "Lama", bn: "লামা" },
    { value: "Naikhongchhari", bn: "নাইক্ষ্যংছড়ি" },
    { value: "Alikadam", bn: "আলীকদম" },
    { value: "Rowangchhari", bn: "রোয়াংছড়ি" },
    { value: "Ruma", bn: "রুমা" },
  ],
  Khagrachhari: [
    { value: "Khagrachhari Sadar", bn: "খাগড়াছড়ি সদর" },
    { value: "Dighinala", bn: "দীঘিনালা" },
    { value: "Panchhari", bn: "পানছড়ি" },
    { value: "Mahalchhari", bn: "মহালছড়ি" },
    { value: "Matiranga", bn: "মাটিরাঙ্গা" },
    { value: "Manikchhari", bn: "মানিকছড়ি" },
    { value: "Ramgarh", bn: "রামগড়" },
    { value: "Lakshmichhari", bn: "লক্ষ্মীছড়ি" },
    { value: "Guimara", bn: "গুইমারা" },
  ],
  Rangamati: [
    { value: "Rangamati Sadar", bn: "রাঙ্গামাটি সদর" },
    { value: "Kaptai", bn: "কাপ্তাই" },
    { value: "Kawkhali", bn: "কাউখালী" },
    { value: "Baghaichhari", bn: "বাঘাইছড়ি" },
    { value: "Barkal", bn: "বরকল" },
    { value: "Juraichhari", bn: "জুরাছড়ি" },
    { value: "Rajasthali", bn: "রাজস্থলী" },
    { value: "Bilaichhari", bn: "বিলাইছড়ি" },
    { value: "Longadu", bn: "লংগদু" },
    { value: "Naniarchar", bn: "নানিয়ারচর" },
  ],
  Feni: [
    { value: "Feni Sadar", bn: "ফেনী সদর" },
    { value: "Chhagalnaiya", bn: "ছাগলনাইয়া" },
    { value: "Sonagazi", bn: "সোনাগাজী" },
    { value: "Fulgazi", bn: "ফুলগাজী" },
    { value: "Parshuram", bn: "পরশুরাম" },
    { value: "Daganbhuiyan", bn: "দাগনভূঞা" },
  ],
  Lakshmipur: [
    { value: "Lakshmipur Sadar", bn: "লক্ষ্মীপুর সদর" },
    { value: "Raipur", bn: "রায়পুর" },
    { value: "Ramganj", bn: "রামগঞ্জ" },
    { value: "Ramgati", bn: "রামগতি" },
    { value: "Kamalnagar", bn: "কমলনগর" },
  ],
  Cumilla: [
    { value: "Cumilla Sadar", bn: "কুমিল্লা সদর" },
    { value: "Debidwar", bn: "দেবিদ্বার" },
    { value: "Muradnagar", bn: "মুরাদনগর" },
    { value: "Chandina", bn: "চান্দিনা" },
    { value: "Burichang", bn: "বুড়িচং" },
    { value: "Brahmanpara", bn: "ব্রাহ্মণপাড়া" },
    { value: "Barura", bn: "বরুড়া" },
    { value: "Nangalkot", bn: "নাঙ্গলকোট" },
    { value: "Chouddagram", bn: "চৌদ্দগ্রাম" },
    { value: "Laksam", bn: "লাকসাম" },
    { value: "Monohorganj", bn: "মনোহরগঞ্জ" },
    { value: "Daudkandi", bn: "দাউদকান্দি" },
    { value: "Titas", bn: "তিতাস" },
    { value: "Homna", bn: "হোমনা" },
    { value: "Meghna", bn: "মেঘনা" },
    { value: "Cumilla Sadar Dakshin", bn: "কুমিল্লা সদর দক্ষিণ" },
    { value: "Lalmai", bn: "লালমাই" },
  ],
  Noakhali: [
    { value: "Noakhali Sadar", bn: "নোয়াখালী সদর" },
    { value: "Begumganj", bn: "বেগমগঞ্জ" },
    { value: "Chatkhil", bn: "চাটখিল" },
    { value: "Senbag", bn: "সেনবাগ" },
    { value: "Sonaimuri", bn: "সোনাইমুড়ী" },
    { value: "Subarnachar", bn: "সুবর্ণচর" },
    { value: "Hatiya", bn: "হাতিয়া" },
    { value: "Kabirhat", bn: "কবিরহাট" },
    { value: "Companiganj", bn: "কোম্পানীগঞ্জ" },
  ],
  Chandpur: [
    { value: "Chandpur Sadar", bn: "চাঁদপুর সদর" },
    { value: "Faridganj", bn: "ফরিদগঞ্জ" },
    { value: "Haimchar", bn: "হাইমচর" },
    { value: "Hajiganj", bn: "হাজীগঞ্জ" },
    { value: "Kachua", bn: "কচুয়া" },
    { value: "Matlab Uttar", bn: "মতলব উত্তর" },
    { value: "Matlab Dakshin", bn: "মতলব দক্ষিণ" },
    { value: "Shahrasti", bn: "শাহরাস্তি" },
  ],
  Brahmanbaria: [
    { value: "Brahmanbaria Sadar", bn: "ব্রাহ্মণবাড়িয়া সদর" },
    { value: "Ashuganj", bn: "আশুগঞ্জ" },
    { value: "Nasirnagar", bn: "নাসিরনগর" },
    { value: "Nabinagar", bn: "নবীনগর" },
    { value: "Sarail", bn: "সরাইল" },
    { value: "Bancharampur", bn: "বাঞ্ছারামপুর" },
    { value: "Kasba", bn: "কসবা" },
    { value: "Akhaura", bn: "আখাউড়া" },
    { value: "Bijoynagar", bn: "বিজয়নগর" },
  ],

  // ---------------- Rajshahi Division ----------------
  Rajshahi: [
    { value: "Rajshahi Sadar", bn: "রাজশাহী সদর" },
    { value: "Godagari", bn: "গোদাগাড়ী" },
    { value: "Tanore", bn: "তানোর" },
    { value: "Paba", bn: "পবা" },
    { value: "Mohanpur", bn: "মোহনপুর" },
    { value: "Bagmara", bn: "বাগমারা" },
    { value: "Durgapur", bn: "দুর্গাপুর" },
    { value: "Puthia", bn: "পুঠিয়া" },
    { value: "Charghat", bn: "চারঘাট" },
    { value: "Bagha", bn: "বাঘা" },
  ],
  Natore: [
    { value: "Natore Sadar", bn: "নাটোর সদর" },
    { value: "Singra", bn: "সিংড়া" },
    { value: "Baraigram", bn: "বড়াইগ্রাম" },
    { value: "Bagatipara", bn: "বাগাতিপাড়া" },
    { value: "Lalpur", bn: "লালপুর" },
    { value: "Gurudaspur", bn: "গুরুদাসপুর" },
    { value: "Naldanga", bn: "নলডাঙ্গা" },
  ],
  Naogaon: [
    { value: "Naogaon Sadar", bn: "নওগাঁ সদর" },
    { value: "Mahadebpur", bn: "মহাদেবপুর" },
    { value: "Patnitala", bn: "পত্নীতলা" },
    { value: "Dhamoirhat", bn: "ধামইরহাট" },
    { value: "Sapahar", bn: "সাপাহার" },
    { value: "Porsha", bn: "পোরশা" },
    { value: "Manda", bn: "মান্দা" },
    { value: "Niamatpur", bn: "নিয়ামতপুর" },
    { value: "Atrai", bn: "আত্রাই" },
    { value: "Raninagar", bn: "রাণীনগর" },
    { value: "Badalgachhi", bn: "বদলগাছী" },
  ],
  Chapainawabganj: [
    { value: "Chapainawabganj Sadar", bn: "চাঁপাইনবাবগঞ্জ সদর" },
    { value: "Shibganj", bn: "শিবগঞ্জ" },
    { value: "Gomastapur", bn: "গোমস্তাপুর" },
    { value: "Nachole", bn: "নাচোল" },
    { value: "Bholahat", bn: "ভোলাহাট" },
  ],
  Pabna: [
    { value: "Pabna Sadar", bn: "পাবনা সদর" },
    { value: "Sujanagar", bn: "সুজানগর" },
    { value: "Ishwardi", bn: "ঈশ্বরদী" },
    { value: "Bhangura", bn: "ভাঙ্গুড়া" },
    { value: "Atgharia", bn: "আটঘরিয়া" },
    { value: "Chatmohar", bn: "চাটমোহর" },
    { value: "Santhia", bn: "সাঁথিয়া" },
    { value: "Faridpur", bn: "ফরিদপুর" },
    { value: "Bera", bn: "বেড়া" },
  ],
  Bogura: [
    { value: "Bogura Sadar", bn: "বগুড়া সদর" },
    { value: "Sherpur", bn: "শেরপুর" },
    { value: "Dhunat", bn: "ধুনট" },
    { value: "Sariakandi", bn: "সারিয়াকান্দি" },
    { value: "Sonatala", bn: "সোনাতলা" },
    { value: "Gabtali", bn: "গাবতলী" },
    { value: "Shibganj", bn: "শিবগঞ্জ" },
    { value: "Kahaloo", bn: "কাহালু" },
    { value: "Dupchanchia", bn: "দুপচাঁচিয়া" },
    { value: "Adamdighi", bn: "আদমদীঘি" },
    { value: "Nandigram", bn: "নন্দীগ্রাম" },
    { value: "Shajahanpur", bn: "শাজাহানপুর" },
  ],
  Sirajganj: [
    { value: "Sirajganj Sadar", bn: "সিরাজগঞ্জ সদর" },
    { value: "Belkuchi", bn: "বেলকুচি" },
    { value: "Chauhali", bn: "চৌহালি" },
    { value: "Kamarkhanda", bn: "কামারখন্দ" },
    { value: "Kazipur", bn: "কাজীপুর" },
    { value: "Raiganj", bn: "রায়গঞ্জ" },
    { value: "Shahjadpur", bn: "শাহজাদপুর" },
    { value: "Tarash", bn: "তাড়াশ" },
    { value: "Ullapara", bn: "উল্লাপাড়া" },
  ],
  Joypurhat: [
    { value: "Joypurhat Sadar", bn: "জয়পুরহাট সদর" },
    { value: "Akkelpur", bn: "আক্কেলপুর" },
    { value: "Kalai", bn: "কালাই" },
    { value: "Khetlal", bn: "ক্ষেতলাল" },
    { value: "Panchbibi", bn: "পাঁচবিবি" },
  ],

  // ---------------- Khulna Division ----------------
  Khulna: [
    { value: "Khulna Sadar", bn: "খুলনা সদর" },
    { value: "Dumuria", bn: "ডুমুরিয়া" },
    { value: "Phultala", bn: "ফুলতলা" },
    { value: "Dighalia", bn: "দিঘলিয়া" },
    { value: "Rupsha", bn: "রূপসা" },
    { value: "Terokhada", bn: "তেরখাদা" },
    { value: "Batiaghata", bn: "বটিয়াঘাটা" },
    { value: "Dacope", bn: "দাকোপ" },
    { value: "Paikgachha", bn: "পাইকগাছা" },
    { value: "Koyra", bn: "কয়রা" },
  ],
  Bagerhat: [
    { value: "Bagerhat Sadar", bn: "বাগেরহাট সদর" },
    { value: "Mollahat", bn: "মোল্লাহাট" },
    { value: "Mongla", bn: "মোংলা" },
    { value: "Rampal", bn: "রামপাল" },
    { value: "Fakirhat", bn: "ফকিরহাট" },
    { value: "Chitalmari", bn: "চিতলমারী" },
    { value: "Kachua", bn: "কচুয়া" },
    { value: "Morrelganj", bn: "মোড়েলগঞ্জ" },
    { value: "Sharankhola", bn: "শরণখোলা" },
  ],
  Satkhira: [
    { value: "Satkhira Sadar", bn: "সাতক্ষীরা সদর" },
    { value: "Assasuni", bn: "আশাশুনি" },
    { value: "Debhata", bn: "দেবহাটা" },
    { value: "Kalaroa", bn: "কলারোয়া" },
    { value: "Kaliganj", bn: "কালিগঞ্জ" },
    { value: "Shyamnagar", bn: "শ্যামনগর" },
    { value: "Tala", bn: "তালা" },
  ],
  Jashore: [
    { value: "Jashore Sadar", bn: "যশোর সদর" },
    { value: "Manirampur", bn: "মণিরামপুর" },
    { value: "Abhaynagar", bn: "অভয়নগর" },
    { value: "Bagharpara", bn: "বাঘারপাড়া" },
    { value: "Chougachha", bn: "চৌগাছা" },
    { value: "Jhikargachha", bn: "ঝিকরগাছা" },
    { value: "Keshabpur", bn: "কেশবপুর" },
    { value: "Sharsha", bn: "শার্শা" },
  ],
  Magura: [
    { value: "Magura Sadar", bn: "মাগুরা সদর" },
    { value: "Mohammadpur", bn: "মহম্মদপুর" },
    { value: "Shalikha", bn: "শালিখা" },
    { value: "Sreepur", bn: "শ্রীপুর" },
  ],
  Jhenaidah: [
    { value: "Jhenaidah Sadar", bn: "ঝিনাইদহ সদর" },
    { value: "Shailkupa", bn: "শৈলকুপা" },
    { value: "Harinakunda", bn: "হরিণাকুন্ডু" },
    { value: "Kaliganj", bn: "কালীগঞ্জ" },
    { value: "Kotchandpur", bn: "কোটচাঁদপুর" },
    { value: "Maheshpur", bn: "মহেশপুর" },
  ],
  Narail: [
    { value: "Narail Sadar", bn: "নড়াইল সদর" },
    { value: "Kalia", bn: "কালিয়া" },
    { value: "Lohagara", bn: "লোহাগড়া" },
  ],
  Kushtia: [
    { value: "Kushtia Sadar", bn: "কুষ্টিয়া সদর" },
    { value: "Kumarkhali", bn: "কুমারখালী" },
    { value: "Khoksa", bn: "খোকসা" },
    { value: "Mirpur", bn: "মিরপুর" },
    { value: "Daulatpur", bn: "দৌলতপুর" },
    { value: "Bheramara", bn: "ভেড়ামারা" },
  ],
  Chuadanga: [
    { value: "Chuadanga Sadar", bn: "চুয়াডাঙ্গা সদর" },
    { value: "Alamdanga", bn: "আলমডাঙ্গা" },
    { value: "Damurhuda", bn: "দামুড়হুদা" },
    { value: "Jibannagar", bn: "জীবননগর" },
  ],
  Meherpur: [
    { value: "Meherpur Sadar", bn: "মেহেরপুর সদর" },
    { value: "Gangni", bn: "গাংনী" },
    { value: "Mujibnagar", bn: "মুজিবনগর" },
  ],

  // ---------------- Barishal Division ----------------
  Barishal: [
    { value: "Barishal Sadar", bn: "বরিশাল সদর" },
    { value: "Bakerganj", bn: "বাকেরগঞ্জ" },
    { value: "Babuganj", bn: "বাবুগঞ্জ" },
    { value: "Banaripara", bn: "বানারীপাড়া" },
    { value: "Gournadi", bn: "গৌরনদী" },
    { value: "Hizla", bn: "হিজলা" },
    { value: "Mehendiganj", bn: "মেহেন্দিগঞ্জ" },
    { value: "Muladi", bn: "মুলাদী" },
    { value: "Wazirpur", bn: "উজিরপুর" },
    { value: "Agailjhara", bn: "আগৈলঝাড়া" },
  ],
  Bhola: [
    { value: "Bhola Sadar", bn: "ভোলা সদর" },
    { value: "Borhanuddin", bn: "বোরহানউদ্দিন" },
    { value: "Charfasson", bn: "চরফ্যাশন" },
    { value: "Daulatkhan", bn: "দৌলতখান" },
    { value: "Lalmohan", bn: "লালমোহন" },
    { value: "Manpura", bn: "মনপুরা" },
    { value: "Tazumuddin", bn: "তজুমদ্দিন" },
  ],
  Patuakhali: [
    { value: "Patuakhali Sadar", bn: "পটুয়াখালী সদর" },
    { value: "Bauphal", bn: "বাউফল" },
    { value: "Dashmina", bn: "দশমিনা" },
    { value: "Galachipa", bn: "গলাচিপা" },
    { value: "Kalapara", bn: "কলাপাড়া" },
    { value: "Mirzaganj", bn: "মির্জাগঞ্জ" },
    { value: "Dumki", bn: "দুমকি" },
    { value: "Rangabali", bn: "রাঙ্গাবালী" },
  ],
  Pirojpur: [
    { value: "Pirojpur Sadar", bn: "পিরোজপুর সদর" },
    { value: "Nazirpur", bn: "নাজিরপুর" },
    { value: "Nesarabad", bn: "নেছারাবাদ" },
    { value: "Bhandaria", bn: "ভান্ডারিয়া" },
    { value: "Kawkhali", bn: "কাউখালী" },
    { value: "Mathbaria", bn: "মঠবাড়িয়া" },
    { value: "Indurkani", bn: "ইন্দুরকানী" },
  ],
  Barguna: [
    { value: "Barguna Sadar", bn: "বরগুনা সদর" },
    { value: "Amtali", bn: "আমতলী" },
    { value: "Bamna", bn: "বামনা" },
    { value: "Betagi", bn: "বেতাগী" },
    { value: "Pathorghata", bn: "পাথরঘাটা" },
    { value: "Taltali", bn: "তালতলী" },
  ],
  Jhalokati: [
    { value: "Jhalokati Sadar", bn: "ঝালকাঠি সদর" },
    { value: "Kathalia", bn: "কাঠালিয়া" },
    { value: "Nalchity", bn: "নলছিটি" },
    { value: "Rajapur", bn: "রাজাপুর" },
  ],

  // ---------------- Sylhet Division ----------------
  Sylhet: [
    { value: "Sylhet Sadar", bn: "সিলেট সদর" },
    { value: "Beanibazar", bn: "বিয়ানীবাজার" },
    { value: "Bishwanath", bn: "বিশ্বনাথ" },
    { value: "Companiganj", bn: "কোম্পানীগঞ্জ" },
    { value: "Fenchuganj", bn: "ফেঞ্চুগঞ্জ" },
    { value: "Golapganj", bn: "গোলাপগঞ্জ" },
    { value: "Gowainghat", bn: "গোয়াইনঘাট" },
    { value: "Jaintiapur", bn: "জৈন্তাপুর" },
    { value: "Kanaighat", bn: "কানাইঘাট" },
    { value: "Zakiganj", bn: "জকিগঞ্জ" },
    { value: "Balaganj", bn: "বালাগঞ্জ" },
    { value: "Osmaninagar", bn: "ওসমানীনগর" },
    { value: "Dakshin Surma", bn: "দক্ষিণ সুরমা" },
  ],
  Moulvibazar: [
    { value: "Moulvibazar Sadar", bn: "মৌলভীবাজার সদর" },
    { value: "Barlekha", bn: "বড়লেখা" },
    { value: "Kamalganj", bn: "কমলগঞ্জ" },
    { value: "Kulaura", bn: "কুলাউড়া" },
    { value: "Rajnagar", bn: "রাজনগর" },
    { value: "Sreemangal", bn: "শ্রীমঙ্গল" },
    { value: "Juri", bn: "জুড়ী" },
  ],
  Habiganj: [
    { value: "Habiganj Sadar", bn: "হবিগঞ্জ সদর" },
    { value: "Ajmiriganj", bn: "আজমিরীগঞ্জ" },
    { value: "Bahubal", bn: "বাহুবল" },
    { value: "Baniachong", bn: "বানিয়াচং" },
    { value: "Chunarughat", bn: "চুনারুঘাট" },
    { value: "Lakhai", bn: "লাখাই" },
    { value: "Madhabpur", bn: "মাধবপুর" },
    { value: "Nabiganj", bn: "নবীগঞ্জ" },
    { value: "Shaistaganj", bn: "শায়েস্তাগঞ্জ" },
  ],
  Sunamganj: [
    { value: "Sunamganj Sadar", bn: "সুনামগঞ্জ সদর" },
    { value: "Bishwambarpur", bn: "বিশ্বম্ভরপুর" },
    { value: "Chhatak", bn: "ছাতক" },
    { value: "Dowarabazar", bn: "দোয়ারাবাজার" },
    { value: "Dharmapasha", bn: "ধর্মপাশা" },
    { value: "Jagannathpur", bn: "জগন্নাথপুর" },
    { value: "Jamalganj", bn: "জামালগঞ্জ" },
    { value: "Shalla", bn: "শাল্লা" },
    { value: "Tahirpur", bn: "তাহিরপুর" },
    { value: "Dirai", bn: "দিরাই" },
    { value: "Madhyanagar", bn: "মধ্যনগর" },
  ],

  // ---------------- Rangpur Division ----------------
  Rangpur: [
    { value: "Rangpur Sadar", bn: "রংপুর সদর" },
    { value: "Badarganj", bn: "বদরগঞ্জ" },
    { value: "Gangachara", bn: "গংগাচড়া" },
    { value: "Kaunia", bn: "কাউনিয়া" },
    { value: "Mithapukur", bn: "মিঠাপুকুর" },
    { value: "Pirgachha", bn: "পীরগাছা" },
    { value: "Pirganj", bn: "পীরগঞ্জ" },
    { value: "Taraganj", bn: "তারাগঞ্জ" },
  ],
  Dinajpur: [
    { value: "Dinajpur Sadar", bn: "দিনাজপুর সদর" },
    { value: "Birampur", bn: "বিরামপুর" },
    { value: "Biral", bn: "বিরল" },
    { value: "Bochaganj", bn: "বোচাগঞ্জ" },
    { value: "Chirirbandar", bn: "চিরিরবন্দর" },
    { value: "Fulbari", bn: "ফুলবাড়ী" },
    { value: "Ghoraghat", bn: "ঘোড়াঘাট" },
    { value: "Hakimpur", bn: "হাকিমপুর" },
    { value: "Kaharole", bn: "কাহারোল" },
    { value: "Khansama", bn: "খানসামা" },
    { value: "Nawabganj", bn: "নবাবগঞ্জ" },
    { value: "Parbatipur", bn: "পার্বতীপুর" },
    { value: "Birganj", bn: "বীরগঞ্জ" },
  ],
  Gaibandha: [
    { value: "Gaibandha Sadar", bn: "গাইবান্ধা সদর" },
    { value: "Fulchhari", bn: "ফুলছড়ি" },
    { value: "Gobindaganj", bn: "গোবিন্দগঞ্জ" },
    { value: "Palashbari", bn: "পলাশবাড়ী" },
    { value: "Saghata", bn: "সাঘাটা" },
    { value: "Sadullapur", bn: "সাদুল্লাপুর" },
    { value: "Sundarganj", bn: "সুন্দরগঞ্জ" },
  ],
  Kurigram: [
    { value: "Kurigram Sadar", bn: "কুড়িগ্রাম সদর" },
    { value: "Nageshwari", bn: "নাগেশ্বরী" },
    { value: "Bhurungamari", bn: "ভুরুঙ্গামারী" },
    { value: "Fulbari", bn: "ফুলবাড়ী" },
    { value: "Rajarhat", bn: "রাজারহাট" },
    { value: "Ulipur", bn: "উলিপুর" },
    { value: "Chilmari", bn: "চিলমারী" },
    { value: "Roumari", bn: "রৌমারী" },
    { value: "Rajibpur", bn: "রাজীবপুর" },
  ],
  Lalmonirhat: [
    { value: "Lalmonirhat Sadar", bn: "লালমনিরহাট সদর" },
    { value: "Aditmari", bn: "আদিতমারী" },
    { value: "Kaliganj", bn: "কালীগঞ্জ" },
    { value: "Hatibandha", bn: "হাতীবান্ধা" },
    { value: "Patgram", bn: "পাটগ্রাম" },
  ],
  Nilphamari: [
    { value: "Nilphamari Sadar", bn: "নীলফামারী সদর" },
    { value: "Dimla", bn: "ডিমলা" },
    { value: "Domar", bn: "ডোমার" },
    { value: "Jaldhaka", bn: "জলঢাকা" },
    { value: "Kishoreganj", bn: "কিশোরগঞ্জ" },
    { value: "Saidpur", bn: "সৈয়দপুর" },
  ],
  Panchagarh: [
    { value: "Panchagarh Sadar", bn: "পঞ্চগড় সদর" },
    { value: "Atwari", bn: "আটোয়ারী" },
    { value: "Boda", bn: "বোদা" },
    { value: "Debiganj", bn: "দেবীগঞ্জ" },
    { value: "Tetulia", bn: "তেঁতুলিয়া" },
  ],
  Thakurgaon: [
    { value: "Thakurgaon Sadar", bn: "ঠাকুরগাঁও সদর" },
    { value: "Baliadangi", bn: "বালিয়াডাঙ্গী" },
    { value: "Haripur", bn: "হরিপুর" },
    { value: "Pirganj", bn: "পীরগঞ্জ" },
    { value: "Ranisankail", bn: "রাণীশংকৈল" },
  ],

  // ---------------- Mymensingh Division ----------------
  Mymensingh: [
    { value: "Mymensingh Sadar", bn: "ময়মনসিংহ সদর" },
    { value: "Trishal", bn: "ত্রিশাল" },
    { value: "Bhaluka", bn: "ভালুকা" },
    { value: "Muktagachha", bn: "মুক্তাগাছা" },
    { value: "Fulbaria", bn: "ফুলবাড়িয়া" },
    { value: "Gaffargaon", bn: "গফরগাঁও" },
    { value: "Gauripur", bn: "গৌরীপুর" },
    { value: "Ishwarganj", bn: "ঈশ্বরগঞ্জ" },
    { value: "Nandail", bn: "নান্দাইল" },
    { value: "Tarakanda", bn: "তারাকান্দা" },
    { value: "Fulpur", bn: "ফুলপুর" },
    { value: "Haluaghat", bn: "হালুয়াঘাট" },
    { value: "Dhobaura", bn: "ধোবাউড়া" },
  ],
  Jamalpur: [
    { value: "Jamalpur Sadar", bn: "জামালপুর সদর" },
    { value: "Bakshiganj", bn: "বকশীগঞ্জ" },
    { value: "Dewanganj", bn: "দেওয়ানগঞ্জ" },
    { value: "Islampur", bn: "ইসলামপুর" },
    { value: "Madarganj", bn: "মাদারগঞ্জ" },
    { value: "Melandaha", bn: "মেলান্দহ" },
    { value: "Sarishabari", bn: "সরিষাবাড়ী" },
  ],
  Netrokona: [
    { value: "Netrokona Sadar", bn: "নেত্রকোণা সদর" },
    { value: "Atpara", bn: "আটপাড়া" },
    { value: "Barhatta", bn: "বারহাট্টা" },
    { value: "Durgapur", bn: "দুর্গাপুর" },
    { value: "Khaliajuri", bn: "খালিয়াজুরী" },
    { value: "Kalmakanda", bn: "কলমাকান্দা" },
    { value: "Kendua", bn: "কেন্দুয়া" },
    { value: "Madan", bn: "মদন" },
    { value: "Mohanganj", bn: "মোহনগঞ্জ" },
    { value: "Purbadhala", bn: "পূর্বধলা" },
  ],
  Sherpur: [
    { value: "Sherpur Sadar", bn: "শেরপুর সদর" },
    { value: "Nakla", bn: "নকলা" },
    { value: "Nalitabari", bn: "নালিতাবাড়ী" },
    { value: "Sribardi", bn: "শ্রীবরদী" },
    { value: "Jhenaigati", bn: "ঝিনাইগাতী" },
  ],
};

/** All 64 districts (English value + Bengali label), ordered by division. */
export const DISTRICTS: readonly GeoOption[] = [
  { value: "Dhaka", bn: "ঢাকা" },
  { value: "Gazipur", bn: "গাজীপুর" },
  { value: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  { value: "Manikganj", bn: "মানিকগঞ্জ" },
  { value: "Munshiganj", bn: "মুন্সিগঞ্জ" },
  { value: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  { value: "Narsingdi", bn: "নরসিংদী" },
  { value: "Tangail", bn: "টাঙ্গাইল" },
  { value: "Faridpur", bn: "ফরিদপুর" },
  { value: "Gopalganj", bn: "গোপালগঞ্জ" },
  { value: "Madaripur", bn: "মাদারীপুর" },
  { value: "Rajbari", bn: "রাজবাড়ী" },
  { value: "Shariatpur", bn: "শরীয়তপুর" },
  { value: "Chattogram", bn: "চট্টগ্রাম" },
  { value: "Cox's Bazar", bn: "কক্সবাজার" },
  { value: "Bandarban", bn: "বান্দরবান" },
  { value: "Khagrachhari", bn: "খাগড়াছড়ি" },
  { value: "Rangamati", bn: "রাঙ্গামাটি" },
  { value: "Feni", bn: "ফেনী" },
  { value: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  { value: "Cumilla", bn: "কুমিল্লা" },
  { value: "Noakhali", bn: "নোয়াখালী" },
  { value: "Chandpur", bn: "চাঁদপুর" },
  { value: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  { value: "Rajshahi", bn: "রাজশাহী" },
  { value: "Natore", bn: "নাটোর" },
  { value: "Naogaon", bn: "নওগাঁ" },
  { value: "Chapainawabganj", bn: "চাঁপাইনবাবগঞ্জ" },
  { value: "Pabna", bn: "পাবনা" },
  { value: "Bogura", bn: "বগুড়া" },
  { value: "Sirajganj", bn: "সিরাজগঞ্জ" },
  { value: "Joypurhat", bn: "জয়পুরহাট" },
  { value: "Khulna", bn: "খুলনা" },
  { value: "Bagerhat", bn: "বাগেরহাট" },
  { value: "Satkhira", bn: "সাতক্ষীরা" },
  { value: "Jashore", bn: "যশোর" },
  { value: "Magura", bn: "মাগুরা" },
  { value: "Jhenaidah", bn: "ঝিনাইদহ" },
  { value: "Narail", bn: "নড়াইল" },
  { value: "Kushtia", bn: "কুষ্টিয়া" },
  { value: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  { value: "Meherpur", bn: "মেহেরপুর" },
  { value: "Barishal", bn: "বরিশাল" },
  { value: "Bhola", bn: "ভোলা" },
  { value: "Patuakhali", bn: "পটুয়াখালী" },
  { value: "Pirojpur", bn: "পিরোজপুর" },
  { value: "Barguna", bn: "বরগুনা" },
  { value: "Jhalokati", bn: "ঝালকাঠি" },
  { value: "Sylhet", bn: "সিলেট" },
  { value: "Moulvibazar", bn: "মৌলভীবাজার" },
  { value: "Habiganj", bn: "হবিগঞ্জ" },
  { value: "Sunamganj", bn: "সুনামগঞ্জ" },
  { value: "Rangpur", bn: "রংপুর" },
  { value: "Dinajpur", bn: "দিনাজপুর" },
  { value: "Gaibandha", bn: "গাইবান্ধা" },
  { value: "Kurigram", bn: "কুড়িগ্রাম" },
  { value: "Lalmonirhat", bn: "লালমনিরহাট" },
  { value: "Nilphamari", bn: "নীলফামারী" },
  { value: "Panchagarh", bn: "পঞ্চগড়" },
  { value: "Thakurgaon", bn: "ঠাকুরগাঁও" },
  { value: "Mymensingh", bn: "ময়মনসিংহ" },
  { value: "Jamalpur", bn: "জামালপুর" },
  { value: "Netrokona", bn: "নেত্রকোণা" },
  { value: "Sherpur", bn: "শেরপুর" },
];

/** Flat list of every upazila across all districts (for label lookup). */
export const ALL_UPAZILAS: readonly GeoOption[] = Object.values(
  UPAZILAS_BY_DISTRICT,
).flat();

/** Upazilas for a district value (empty when unknown/unselected). */
export function upazilasFor(district: string): readonly GeoOption[] {
  return UPAZILAS_BY_DISTRICT[district] ?? [];
}
